### PR TITLE
Callback threading issues fixed #54

### LINKED ISSUE #54: Callback threading problems
Hi,

I just discovered an issue with the callbacks. Please run my test a couple of times in order to see what's going on (sometimes it'll fail, but sometimes it won't):

```swift
func testQueues() {
    var then: DispatchTime!
    var always: DispatchTime!
    weak var expectation = self.expectation(description: "Threading is hard!")
    Promise(value: 1)
    .then(on: DispatchQueue.global(qos: .default), { value in
        return 2
    })
    .then(on: DispatchQueue.global(qos: .background)) { value -> Promise<Int> in
        return Promise<Int>(queue: .main) { s, f in
            DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(3)) {
                s(3)
            }
        }
    }
    .then(on: DispatchQueue.global(qos: .background)) { value in
        return 4
    }
    .then(on: DispatchQueue.global(qos: .utility), { value in
        then = DispatchTime.now()
    })
    .catch(on: DispatchQueue.global(qos: .default)) { err in
        // do nothing, won't fail
    }
    .then(on: DispatchQueue.global(qos: .default)) { value in
        always = DispatchTime.now()
        XCTAssert(then != nil)
        XCTAssert(always > then)
        expectation?.fulfill()
    }
    waitForExpectations(timeout: 5, handler: nil)
}
```

The source of this problem is here:

```swift
private func fireCallbacksIfCompleted() {
    lockQueue.async(execute: {
        guard !self.state.isPending else { return }
        self.callbacks.forEach { callback in
            switch self.state {
            case let .fulfilled(value):
                callback.callFulfill(value)
            case let .rejected(error):
                callback.callReject(error)
            default:
                break
            }
        }
        self.callbacks.removeAll()
    })
}
```

This method won't wait for the previous callback to finish, so if the actual execution is on multiple threads, the callback order can be messed up. It's a pretty nasty bug. 🐛🙃

I'd suggest to use a DispatchGroup so you could get notified after a callback finished it's work. Also If you have a better alternative in order to fix this, please let me know. Thanks! 👍

### PR DESCRIPTION
**Pull request by tib**
This PR fixes an issue with threads & callback execution orders by using a DispatchGroup and a new queue property on the ExecitionContext.

### CODE REVIEW

**Comment by khanlou** [comment]
Closes #54

File: Promise/Promise.swift [hunk 1]
```diff
@@ -12,10 +12,16 @@ import Foundation
...
+    var queue: DispatchQueue { get }
     func execute(_ work: @escaping () -> Void)
 }
 
 extension DispatchQueue: ExecutionContext {
+
+    public var queue: DispatchQueue {
+        return self
+    }
+
```
Comment (khanlou) [inline Promise/Promise.swift]: I worry about coupling execution contexts too much to DispatchQueues. I was thinking we should add a completion block to the execute function or the callFulfill/callReject functions. Would that make sense?

**Review by khanlou — COMMENTED** [review]
Can you bring your test into the test suite as well? Loop it a few times if needed so that we can be sure that it's failing

File: Promise/Promise.swift (hunk 1 above)
Comment (tib) [reply Promise/Promise.swift]: I did the required changes, please check out the last commit. 😉

**Review by khanlou — APPROVED** [review]
